### ISSUE TITLE
Some questions about "Variational PatchMatch MultiView Reconstruction and Refinement"

### ISSUE THREAD

**Issue by llcc343** [phheise/cvt#3]
Hi Philipp,
      I have carefully studied your execellent paper “Variational PatchMatch MultiView Reconstruction and Refinement”. And I still have some questions about the depthmap fusion.
     1. Which kind of initialization is reasonable?
     2. Could EM algorithm be used in Geoerge Vogiatzis’model?
     I am studying an visual odometry algorithm (named svo) which uses an Bayesian model proposed by Geoerge Vogiatzis to update features’depth. But I found only a small part of seeds converged in every update progress. Even if I tried to update the newly inserted seeds using the previous overlap keyframes , it seems that this strategy does not help too much. 
     Is this phenomenon normal?
     How to define the variance in the Gaussian mixture model? Does the variance have a great influence on the converge performance ?
     Do you have some suggestions for how to improve the performance of probabilistic Bayesian mode?
     Looking forward to your quick reply:)

**Comment by phheise** [comment]
I makes sense to initialize with a high variance and when enough samples have been observed the variance will automatically adapt and converge. One crucial problem is that if the first sample is incorrect and a low variance is used that the responsibility evaluates to a very small value or zero and thus the mean and variance are not changed at all or very many samples are necessary. Therefore it is also important that the variance becomes not to small or that the responsibility is set to a certain minimum value. Otherwise convergence will take a very long time or not happen at all and the values stick to the first observation.

You can easily artificially generate samples that follow the Gaussian plus Uniform noise mixture model and compare the models from our paper and e.g. SVO. I found it very useful to plot the results with respect to the number of samples together with the estimated variance. That way you should also be able to adjust the aforementioned parameters to some meaningful values.
